version: '3.7'

services:
    backend:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        restart: always
        ports:
            - "8000:8000"
        #network_mode: 'host'
